version: '3.8'
services:

  app-reactive:
    container_name: app-reactive
    build:
      context: .
      dockerfile: Dockerfile
    image: app-reactive:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ~src/main/resources/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"

volumes:
  mongodata:
  prometheus_data:
  grafana_data: